### ISSUE TITLE
frequency distributions in R question 28

### ISSUE THREAD

**Issue by SamJonesColumbia21** [jtr13/1201#11]
For Question 28 in section 1.2, how can we translate this:

1.0− , 2.0 5 2.4− , 2.6 13 2.8− , 3.0 46 3.2− , 3.4 133 3.6− , 3.8 126 4.0− , 4.2 73 4.4− , 4.6 19
2.0− , 2.4 11 2.6− , 2.8 30 3.0− , 3.2 66 3.4− , 3.6 141 3.8− , 4.0 92 4.2− , 4.4 38 4.6− , 5.0 11

To data that can be used to make a Histogram in R? I am not sure how to organise the data so as to get the precise bin widths e.g. (1.0, 2.0] and then pair the frequency count with the various bidwidths. 
Thanks!

**Comment by jtr13** [comment]
Unfortunately there's no simple way to deal with both the fact that the data is already binned and that the bins are uneven. One approach would be to unbin the data using the `rep()` function with the midpoints of the bins. For example, suppose the bins are 0-1, 1-3, and 3-7 and the counts are 10, 15, 20. You could do the following:
```
x <- rep(c(.5, 2, 5), c(10, 15, 20))
hist(x, breaks = c(0, 1, 3, 7), col = "lightblue")
```
Note that you don't have to use `freq = FALSE`; it "knows" to do a density histogram due to the uneven binwidths.

**Comment by SamJonesColumbia21** [comment]
Thank you very much I will try this out and get back to you!

**Comment by SamJonesColumbia21** [comment]
Awesome - that worked.
